[platformio]
default_envs = esp12n

[env:esp12n]
platform = espressif8266@4.2.1
board = esp12e
framework = arduino
upload_speed = 460800
monitor_speed = 74880
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
[env:dt06]
platform = espressif8266@4.2.1
board = espmxdevkit
framework = arduino
upload_speed = 115200
monitor_speed = 74880
board_build.f_cpu = 160000000L
board_build.ldscript = eagle.flash.2m512.ld
board_upload.flash_size = 2MB
board_upload.maximum_size = 1044464
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
    -D DT06_BUILD=1
    -D DEVICE_HOSTNAME=\"iotcam-dt06\"